// Mock data for the routing app prototype (no backend yet).
// Swap this out for real Supabase-backed data later — the components only
// care about the shapes below, not where the data comes from.

export const technicians = [
  {
    id: "tech-1",
    name: "Luiz Gustavo",
    role: "Administrator",
    color: "#16A34A",
    phone: "(941) 555-0110",
    van: "Van 02",
    stats: { total: 14, completed: 10, timeLeft: "4h 30m", distance: "32.5 mi" },
  },
  {
    id: "tech-2",
    name: "André Rafael",
    role: "Technician",
    color: "#2563EB",
    phone: "(941) 555-0134",
    van: "Van 04",
    stats: { total: 12, completed: 8, timeLeft: "3h 15m", distance: "27.8 mi" },
  },
  {
    id: "tech-3",
    name: "João Silva",
    role: "Technician",
    color: "#7C3AED",
    phone: "(941) 555-0198",
    van: "Van 01",
    stats: { total: 10, completed: 6, timeLeft: "2h 45m", distance: "21.4 mi" },
  },
];

// mapX / mapY are percentage coordinates (0-100) used to place markers on the
// placeholder MapView. status: "completed" | "current" | "upcoming".
export const stops = [
  {
    id: "stop-1",
    technicianId: "tech-1",
    order: 1,
    clientName: "Jeff Bredley",
    address: "2400 Waterfront Circle, Sarasota, FL 34240",
    area: "Sarasota",
    phone: "(941) 555-2201",
    scheduledTime: "8:00 AM",
    status: "completed",
    poolType: "Residential",
    serviceType: "Weekly Service",
    notes: "",
    mapX: 18,
    mapY: 30,
  },
  {
    id: "stop-2",
    technicianId: "tech-1",
    order: 2,
    clientName: "Maria Rodriguez",
    address: "1254 Lakeview Dr, Sarasota, FL 34243",
    area: "Sarasota",
    phone: "(941) 555-2244",
    scheduledTime: "8:45 AM",
    status: "completed",
    poolType: "Residential",
    serviceType: "Weekly Service",
    notes: "",
    mapX: 24,
    mapY: 36,
  },
  {
    id: "stop-3",
    technicianId: "tech-1",
    order: 3,
    clientName: "David Thompson",
    address: "5678 Palm Aire Dr, Sarasota, FL 34243",
    area: "Sarasota",
    phone: "(941) 555-2309",
    scheduledTime: "9:30 AM",
    status: "current",
    poolType: "Residential",
    serviceType: "Weekly Service",
    notes: "Pool Cleaning & Chemicals",
    mapX: 35,
    mapY: 44,
  },
  {
    id: "stop-4",
    technicianId: "tech-1",
    order: 4,
    clientName: "Linda Parker",
    address: "3412 Pinebrook Rd, Sarasota, FL 34231",
    area: "Sarasota",
    phone: "(941) 555-2278",
    scheduledTime: "10:15 AM",
    status: "upcoming",
    poolType: "Residential",
    serviceType: "Weekly Service",
    notes: "",
    mapX: 33,
    mapY: 56,
  },
  {
    id: "stop-5",
    technicianId: "tech-1",
    order: 5,
    clientName: "Robert Johnson",
    address: "7820 Prestancia Blvd, Sarasota, FL 34238",
    area: "Sarasota",
    phone: "(941) 555-2355",
    scheduledTime: "11:00 AM",
    status: "upcoming",
    poolType: "Residential",
    serviceType: "Weekly Service",
    notes: "Check filter pressure at Stop 5",
    mapX: 42,
    mapY: 66,
  },
  {
    id: "stop-6",
    technicianId: "tech-1",
    order: 6,
    clientName: "Susan Miller",
    address: "4927 River Club Blvd, Bradenton, FL 34202",
    area: "Bradenton",
    phone: "(941) 555-2390",
    scheduledTime: "11:45 AM",
    status: "upcoming",
    poolType: "Residential",
    serviceType: "Pool Service",
    notes: "",
    mapX: 55,
    mapY: 26,
  },
  {
    id: "stop-7",
    technicianId: "tech-1",
    order: 7,
    clientName: "James Wilson",
    address: "2101 Harbor Sound Dr, Longboat Key, FL 34228",
    area: "Longboat Key",
    phone: "(941) 555-2412",
    scheduledTime: "12:30 PM",
    status: "upcoming",
    poolType: "Residential",
    serviceType: "Weekly Service",
    notes: "Gate code 1234",
    mapX: 12,
    mapY: 14,
  },
  {
    id: "stop-8",
    technicianId: "tech-1",
    order: 8,
    clientName: "Patricia Brown",
    address: "6655 Midnight Pass Rd, Sarasota, FL 34242",
    area: "Siesta Key",
    phone: "(941) 555-2467",
    scheduledTime: "1:15 PM",
    status: "upcoming",
    poolType: "Residential",
    serviceType: "Weekly Service",
    notes: "",
    mapX: 20,
    mapY: 74,
  },

  // tech-2 and tech-3 stops exist so the desktop dispatcher view has more
  // than one route to switch between.
  {
    id: "stop-9",
    technicianId: "tech-2",
    order: 1,
    clientName: "Patricia Nolan",
    address: "1980 Bay Front Dr, Osprey, FL 34229",
    area: "Osprey",
    phone: "(941) 555-3301",
    scheduledTime: "8:30 AM",
    status: "completed",
    poolType: "Residential",
    serviceType: "Weekly Service",
    notes: "",
    mapX: 34,
    mapY: 70,
  },
  {
    id: "stop-10",
    technicianId: "tech-2",
    order: 2,
    clientName: "Marcus Reed",
    address: "412 N Indian Ave, Venice, FL 34285",
    area: "Venice",
    phone: "(941) 555-3345",
    scheduledTime: "9:45 AM",
    status: "current",
    poolType: "Residential",
    serviceType: "Equipment Repair",
    notes: "Equipment repair follow-up",
    mapX: 52,
    mapY: 82,
  },
  {
    id: "stop-11",
    technicianId: "tech-2",
    order: 3,
    clientName: "Vista Palms Condominiums",
    address: "2200 Vista Palms Cir, Venice, FL 34293",
    area: "Venice",
    phone: "(941) 555-3378",
    scheduledTime: "11:00 AM",
    status: "upcoming",
    poolType: "Commercial",
    serviceType: "Weekly Service",
    notes: "",
    mapX: 66,
    mapY: 88,
  },

  {
    id: "stop-12",
    technicianId: "tech-3",
    order: 1,
    clientName: "Linda Cho",
    address: "5321 Manatee Ave W, Bradenton, FL 34209",
    area: "Bradenton",
    phone: "(941) 555-4401",
    scheduledTime: "8:00 AM",
    status: "current",
    poolType: "Residential",
    serviceType: "Weekly Service",
    notes: "",
    mapX: 20,
    mapY: 20,
  },
  {
    id: "stop-13",
    technicianId: "tech-3",
    order: 2,
    clientName: "Palmer Ranch Racquet Club",
    address: "5300 Fox Hollow Dr, Sarasota, FL 34238",
    area: "Palmer Ranch",
    phone: "(941) 555-4433",
    scheduledTime: "9:30 AM",
    status: "upcoming",
    poolType: "Commercial",
    serviceType: "Weekly Service",
    notes: "",
    mapX: 44,
    mapY: 60,
  },
];

export const currentLocation = {
  technicianId: "tech-1",
  mapX: 22,
  mapY: 50,
};

// Decorative place-name labels drawn on the placeholder map, roughly
// matching the relative geography of the Sarasota, FL area.
export const mapLabels = [
  { text: "Longboat Key", x: 10, y: 10 },
  { text: "Sarasota", x: 30, y: 40 },
  { text: "Fruitville", x: 62, y: 34 },
  { text: "Bee Ridge", x: 58, y: 58 },
  { text: "Siesta Key", x: 14, y: 78 },
  { text: "Osprey", x: 36, y: 76 },
  { text: "Venice", x: 56, y: 92 },
];

export function stopsFor(technicianId) {
  return stops.filter((s) => s.technicianId === technicianId).sort((a, b) => a.order - b.order);
}

export function statsFor(technicianId) {
  return technicians.find((t) => t.id === technicianId)?.stats ?? { total: 0, completed: 0, timeLeft: "—", distance: "—" };
}
