/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MaintenancePlansRouteImport } from './routes/maintenance-plans'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TecnicoRouteImport } from './routes/tecnico'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedEstimativaRouteImport } from './routes/_authenticated/estimativa'
import { Route as AuthenticatedInvoiceRouteImport } from './routes/_authenticated/invoice'
import { Route as AuthenticatedRotasRouteImport } from './routes/_authenticated/rotas'
import { Route as ETokenRouteImport } from './routes/e.$token'
import { Route as ITokenRouteImport } from './routes/i.$token'
import { Route as AuthenticatedChemicalsStopIdRouteImport } from './routes/_authenticated/chemicals.$stopId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenancePlansRoute = MaintenancePlansRouteImport.update({
  id: '/maintenance-plans',
  path: '/maintenance-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicoRoute = TecnicoRouteImport.update({
  id: '/tecnico',
  path: '/tecnico',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstimativaRoute = AuthenticatedEstimativaRouteImport.update({
  id: '/estimativa',
  path: '/estimativa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoiceRoute = AuthenticatedInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotasRoute = AuthenticatedRotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ETokenRoute = ETokenRouteImport.update({
  id: '/e/$token',
  path: '/e/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ITokenRoute = ITokenRouteImport.update({
  id: '/i/$token',
  path: '/i/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChemicalsStopIdRoute =
  AuthenticatedChemicalsStopIdRouteImport.update({
    id: '/chemicals/$stopId',
    path: '/chemicals/$stopId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/maintenance-plans': typeof MaintenancePlansRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/tecnico': typeof TecnicoRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/estimativa': typeof AuthenticatedEstimativaRoute
  '/invoice': typeof AuthenticatedInvoiceRoute
  '/rotas': typeof AuthenticatedRotasRoute
  '/e/$token': typeof ETokenRoute
  '/i/$token': typeof ITokenRoute
  '/chemicals/$stopId': typeof AuthenticatedChemicalsStopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/maintenance-plans': typeof MaintenancePlansRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/tecnico': typeof TecnicoRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/estimativa': typeof AuthenticatedEstimativaRoute
  '/invoice': typeof AuthenticatedInvoiceRoute
  '/rotas': typeof AuthenticatedRotasRoute
  '/e/$token': typeof ETokenRoute
  '/i/$token': typeof ITokenRoute
  '/chemicals/$stopId': typeof AuthenticatedChemicalsStopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/maintenance-plans': typeof MaintenancePlansRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/tecnico': typeof TecnicoRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/estimativa': typeof AuthenticatedEstimativaRoute
  '/_authenticated/invoice': typeof AuthenticatedInvoiceRoute
  '/_authenticated/rotas': typeof AuthenticatedRotasRoute
  '/e/$token': typeof ETokenRoute
  '/i/$token': typeof ITokenRoute
  '/_authenticated/chemicals/$stopId': typeof AuthenticatedChemicalsStopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/maintenance-plans'
    | '/service-areas'
    | '/services'
    | '/tecnico'
    | '/clientes'
    | '/estimativa'
    | '/invoice'
    | '/rotas'
    | '/e/$token'
    | '/i/$token'
    | '/chemicals/$stopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/maintenance-plans'
    | '/service-areas'
    | '/services'
    | '/tecnico'
    | '/clientes'
    | '/estimativa'
    | '/invoice'
    | '/rotas'
    | '/e/$token'
    | '/i/$token'
    | '/chemicals/$stopId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/maintenance-plans'
    | '/service-areas'
    | '/services'
    | '/tecnico'
    | '/_authenticated/clientes'
    | '/_authenticated/estimativa'
    | '/_authenticated/invoice'
    | '/_authenticated/rotas'
    | '/e/$token'
    | '/i/$token'
    | '/_authenticated/chemicals/$stopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  MaintenancePlansRoute: typeof MaintenancePlansRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  ServicesRoute: typeof ServicesRoute
  TecnicoRoute: typeof TecnicoRoute
  ETokenRoute: typeof ETokenRoute
  ITokenRoute: typeof ITokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance-plans': {
      id: '/maintenance-plans'
      path: '/maintenance-plans'
      fullPath: '/maintenance-plans'
      preLoaderRoute: typeof MaintenancePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnico': {
      id: '/tecnico'
      path: '/tecnico'
      fullPath: '/tecnico'
      preLoaderRoute: typeof TecnicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estimativa': {
      id: '/_authenticated/estimativa'
      path: '/estimativa'
      fullPath: '/estimativa'
      preLoaderRoute: typeof AuthenticatedEstimativaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoice': {
      id: '/_authenticated/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof AuthenticatedInvoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotas': {
      id: '/_authenticated/rotas'
      path: '/rotas'
      fullPath: '/rotas'
      preLoaderRoute: typeof AuthenticatedRotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/e/$token': {
      id: '/e/$token'
      path: '/e/$token'
      fullPath: '/e/$token'
      preLoaderRoute: typeof ETokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$token': {
      id: '/i/$token'
      path: '/i/$token'
      fullPath: '/i/$token'
      preLoaderRoute: typeof ITokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chemicals/$stopId': {
      id: '/_authenticated/chemicals/$stopId'
      path: '/chemicals/$stopId'
      fullPath: '/chemicals/$stopId'
      preLoaderRoute: typeof AuthenticatedChemicalsStopIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedEstimativaRoute: typeof AuthenticatedEstimativaRoute
  AuthenticatedInvoiceRoute: typeof AuthenticatedInvoiceRoute
  AuthenticatedRotasRoute: typeof AuthenticatedRotasRoute
  AuthenticatedChemicalsStopIdRoute: typeof AuthenticatedChemicalsStopIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedEstimativaRoute: AuthenticatedEstimativaRoute,
  AuthenticatedInvoiceRoute: AuthenticatedInvoiceRoute,
  AuthenticatedRotasRoute: AuthenticatedRotasRoute,
  AuthenticatedChemicalsStopIdRoute: AuthenticatedChemicalsStopIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  MaintenancePlansRoute: MaintenancePlansRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  ServicesRoute: ServicesRoute,
  TecnicoRoute: TecnicoRoute,
  ETokenRoute: ETokenRoute,
  ITokenRoute: ITokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
